spring:
  datasource:
    username: root
    password: syxsyx
    url: jdbc:mysql://localhost:3306/bbs?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    cache: false
  messages:
    basename: i18n.login

mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
  type-aliases-package: com.syx.springbootdemo.pojo
